// Palace Types
export const PALACE_UPDATE_STEP = "PALACE_UPDATE_STEP";
export const PALACE_SETUP_GAME = "PALACE_SETUP_GAME";
export const ADD_SELECTED_CARD = "ADD_SELECTED_CARD";
export const REMOVE_SELECTED_CARD = "REMOVE_SELECTED_CARD";
export const SET_TOP_CARDS = "SET_TOP_CARDS";
