// Palace Types
export const PALACE_UPDATE_STEP = "PALACE_UPDATE_STEP";
export const PALACE_SETUP_GAME = "PALACE_SETUP_GAME";
export const ADD_SELECTED_CARD = "ADD_SELECTED_CARD";
export const REMOVE_SELECTED_CARD = "REMOVE_SELECTED_CARD";
export const REMOVE_ALL_SELECTED_CARDS = "REMOVE_ALL_SELECTED_CARDS";
export const UPDATE_PLAYER_TURN = "UPDATE_PLAYER_TURN";
export const PALACE_ROBOT_TOP_THREE_CARDS = "PALACE_ROBOT_TOP_THREE_CARDS";
export const PALACE_ADD_STARTING_CARD = "PALACE_ADD_STARTING_CARD";
export const PALACE_STARTING_TURN = "PALACE_STARTING_TURN";
export const PLAYER_PICKUP_CARDS = "PLAYER_PICKUP_CARDS";
export const PLAYER_PLAYS_CARDS = "PLAYER_PLAYS_CARDS";
